@startmindmap

title "GCP - Vertex AI"
footer Disponível em: https://github.com/acnaweb/vertexai

*[#F8F8FF] Vertex AI

**[#LightGray] Products

***_ ML APÌ
***_ Auto ML
***_ Custom Machine Learning
***_ Vertex AI Features
***_ BigQuery ML

@endmindmap