@startmindmap

title "GCP - Vertex AI"
footer Disponível em: https://github.com/acnaweb/vertexai

*[#F8F8FF] Vertex AI

**[#LightGray] Capabilities

***_ VM: cores + memory

left side

**[#LightGray] (DVM) Dedicated VM Hosts

***_ VM on a Physical Server

@endmindmap